version: '3.7'

services:
  kafka:
    image: lensesio/fast-data-dev:2.2.1
    hostname: localhost
    environment:
      - SAMPLEDATA=0
    ports:
      - '9092:9092'
    healthcheck:
      test: curl --fail http://localhost:8082/topics || exit 1
      interval: 10s
      timeout: 8s
      retries: 15